Update volsync-target Docker tag to v0.6.0 (#2695)
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [volsync-target](https://github.com/backube/volsync) | minor | `0.5.0` -> `0.6.0` |

---

### Release Notes

<details>
<summary>backube/volsync (volsync-target)</summary>

### [`v0.6.0`](https://github.com/backube/volsync/blob/HEAD/CHANGELOG.md#060)

[Compare Source](https://github.com/backube/volsync/compare/v0.5.0...v0.6.0)

##### Added

- restic - allow passing in GOOGLE\_APPLICATION\_CREDENTIALS as a file

##### Changed

- :warning: Breaking change :warning: - Helm chart now manages VolSync CRDs
  directly.\
  Upgrading the VolSync Helm chart from an earlier version will produce the
  following error:

  ```
  Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: CustomResourceDefinition "replicationdestinations.volsync.backube" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "volsync"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "volsync-system"
  ```

  To fix, apply the missing labels and annotations as mentioned in the error
  message (your values may differ), then retry the upgrade:

  ```console
  $ kubectl label crd/replicationdestinations.volsync.backube app.kubernetes.io/managed-by=Helm
  customresourcedefinition.apiextensions.k8s.io/replicationdestinations.volsync.backube labeled
  $ kubectl label crd/replicationsources.volsync.backube app.kubernetes.io/managed-by=Helm
  customresourcedefinition.apiextensions.k8s.io/replicationsources.volsync.backube labeled
  $ kubectl annotate crd/replicationdestinations.volsync.backube meta.helm.sh/release-name=volsync
  customresourcedefinition.apiextensions.k8s.io/replicationdestinations.volsync.backube annotated
  $ kubectl annotate crd/replicationsources.volsync.backube meta.helm.sh/release-name=volsync
  customresourcedefinition.apiextensions.k8s.io/replicationsources.volsync.backube annotated
  $ kubectl annotate crd/replicationdestinations.volsync.backube meta.helm.sh/release-namespace=volsync-system
  customresourcedefinition.apiextensions.k8s.io/replicationdestinations.volsync.backube annotated
  $ kubectl annotate crd/replicationsources.volsync.backube meta.helm.sh/release-namespace=volsync-system
  customresourcedefinition.apiextensions.k8s.io/replicationsources.volsync.backube annotated
  ```

- VolSync privileged mover SCC installed at startup on OpenShift

- Syncthing upgraded to 1.22.1

- Updates to build with golang 1.19

##### Fixed

- ReplicationSource fixes for rsync, rclone and restic to enable mounting
  ROX source PVCs as read-only

##### Security

- rclone mover updated to run with reduced privileges by default
- restic mover updated to run with reduced privileges by default
- syncthing mover updated to run with reduced privileges by default
- kube-rbac-proxy upgraded to 0.13.1

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0Mi4zOS4xIiwidXBkYXRlZEluVmVyIjoiNDIuMzkuMSIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsiaW1hZ2UiXX0=-->

Reviewed-on: https://gitea.alexlebens.dev/alexlebens/infrastructure/pulls/2695
Co-authored-by: Renovate Bot <renovate-bot@alexlebens.net>
Co-committed-by: Renovate Bot <renovate-bot@alexlebens.net>